"""Built-in synonym dictionary for text augmentations."""
from typing import Dict, List

DEFAULT_SYNONYMS: Dict[str, List[str]] = {
    "good": ["great", "fine", "excellent", "superb"],
    "bad": ["poor", "terrible", "awful", "dreadful"],
    "big": ["large", "huge", "enormous", "vast"],
    "small": ["tiny", "little", "minute", "compact"],
    "happy": ["glad", "joyful", "pleased", "cheerful"],
    "sad": ["unhappy", "sorrowful", "gloomy", "blue"],
    "fast": ["quick", "rapid", "swift", "speedy"],
    "slow": ["sluggish", "gradual", "unhurried"],
    "hot": ["warm", "scorching", "heated", "boiling"],
    "cold": ["cool", "chilly", "freezing", "frigid"],
    "old": ["ancient", "aged", "elderly", "vintage"],
    "new": ["fresh", "novel", "recent", "modern"],
    "hard": ["difficult", "tough", "challenging"],
    "easy": ["simple", "effortless", "straightforward"],
    "pretty": ["beautiful", "lovely", "attractive"],
    "ugly": ["hideous", "unsightly", "unattractive"],
    "smart": ["clever", "intelligent", "bright"],
    "stupid": ["foolish", "dumb", "senseless"],
    "strong": ["powerful", "sturdy", "robust"],
    "weak": ["feeble", "frail", "fragile"],
    "rich": ["wealthy", "affluent", "prosperous"],
    "poor": ["needy", "impoverished", "destitute"],
    "clean": ["spotless", "tidy", "pristine"],
    "dirty": ["filthy", "grimy", "soiled"],
    "loud": ["noisy", "booming", "thunderous"],
    "quiet": ["silent", "hushed", "muted"],
    "nice": ["pleasant", "agreeable", "delightful"],
    "mean": ["cruel", "unkind", "harsh"],
    "brave": ["courageous", "fearless", "bold"],
    "scared": ["afraid", "frightened", "terrified"],
}
